### PR TITLE
cli: port to click library

### PR DESCRIPTION
**Pull request by jirikuncar**
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
@jirikuncar Can you please look at fixing those CI errors?  There are several occurrences of:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: 
    ordinal not in range(128)
```

and one hardcoded 2015 year in the copyright test:

```
E       AssertionError: 
E       Expected: a sequence containing '13: L100 license is missing'
E            but: was <['14: L102 copyright year is outdated, expected 2016 but got 2015']>
```

**Comment by tiborsimko** [comment]
- You may also remove `Dockerfile` and `fig.yml` now that server support is gone.

- Can you please amend the commit message to explicitly say more on the motivation: "INCOMPATIBLE Removal of WSGI server support for managing GitHub hooks. The kwalitee tool is to be run only locally from now on."

- Have you observed this?

```console
$ mkvirtualenv test123
$ pip install -e .[tests,docs,gitpython]
Exception:
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/test123/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/simko/.virtualenvs/test123/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/home/simko/.virtualenvs/test123/local/lib/python2.7/site-packages/pip/basecommand.py", line 280, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/simko/.virtualenvs/test123/local/lib/python2.7/site-packages/pip/req/req_install.py", line 136, in from_editable
    editable_req, default_vcs)
  File "/home/simko/.virtualenvs/test123/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1146, in parse_editable
    '__placeholder__' + extras
  File "/home/simko/.virtualenvs/test123/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2806, in parse
    req, = parse_requirements(s)
  File "/home/simko/.virtualenvs/test123/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2754, in parse_requirements
    yield Requirement(line)
  File "/home/simko/.virtualenvs/test123/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2763, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'__placeh'"
```

I need to install gitpython manually... Otherwise LGTM.

**Comment by tiborsimko** [comment]
Also, `tox` does not work because of "optional" pygit2/GitPython deps:

```console
$ tox -e py27
[...]
E       AssertionError: 
E       Expected: <['']>
E            but: was <[u'To use this feature, please install pygit2. GitPython will also work but is not recommended (python <= 2.7 only).', u'']>
```

It may confuse people...

**Comment by jirikuncar** [comment]
Removed Docker related files and fixed tox.

**Pull request merged**
