### PR TITLE
core: pep8 fix

### PR DESCRIPTION
**Pull request by david-caro**
* Fixes some pep8 issues

Signed-off-by: David Caro <dcaroest@redhat.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
`s/core:/global:/`

**Comment by david-caro** [comment]
forgot to push before pull-request...

**Comment by david-caro** [comment]
btw. is there any reason why to obsess with the final dot?

**Comment by jirikuncar** [comment]
Because we generate release notes from commit messages.

**Comment by david-caro** [comment]
Sorry, I don't see the link, can you elaborate?

**Comment by david-caro** [comment]
I still see no reference there at all to the terminating dots requirement or it's rationale :confused:

**Comment by david-caro** [comment]
Ahhh, now I get the signature you were talking about, it's the commit message 'signed-off-by' label, :), changing.

I though you were talking about the pgp signature (I was looking on where did I start adding a pgp signature to my commits...)

**Comment by tiborsimko** [comment]
@david-caro Just to expand a bit on the missing dot part,  in case someone reads this.  The aim is to use proper English grammar so that the sentences would read well "as is", because we generate release notes automatically out of commit log messages. For example try:

```
$ cd private/src/invenio
$ kwalitee prepare release -c v2.1.0..v2.1.1
```
that should give you [Invenio v2.1.1 release notes news](https://github.com/inveniosoftware/invenio/releases/tag/v2.1.1) as whey were published.

This is described briefly in http://invenio.readthedocs.io/en/latest/processes/releasing.html#generate-release-notes

**Comment by david-caro** [comment]
Seems only cosmetic to me (I don't think they had changelogs or commit messages into account when writing down the english grammar rules, and I see no functional benefit for it either), but sure, your project, your rules.

**Comment by tiborsimko** [comment]
The benefit is simply that the generated release notes would contain proper English paragraphs.  E.g. consider this commit message:

- https://github.com/inveniosoftware/invenio/commit/2960c3a1672d662d5d9b08756bb025955636b0ef

that contains multiple sentences, each properly terminated by a dot.  You can include such a paragraph directly  into an "Incompatible changes" section of the release notes documentation, and you are done. 

Another perspective: people are usually writing Sphinx documentation for a package using proper sentence structure, so we also try to write commit log messages using the proper sentence structure too. The benefit being that we can easily generate part of the Sphinx documentation from those commit log messages automatically.

P.S. Yes, it's only cosmetics... but it's benefiting the other persons in the Invenio ecosystem. Getting the commit messages "release announcement ready" right at the development stage (i) helps the original developer to think about how to properly frame the given change, (ii) helps the reviewer, tester, integrator to understand the purpose without knowing/reading its context, (iii) helps the release manager to compile understandable release notes and get the releases out faster.  The proper commit message structure is a tiny investment by the developer, when one gets used to them, that later benefits everyone in our ecosystem, the hopes go...

**Comment by david-caro** [comment]
So, all that is true too, as long as you are able to "ignore" the lack of dots at the end of the bulleted list right? I mean, a release notes, where clearly separated bulleted sections don't end with a dot, it's 100% clear and acceptable imo. And if you are able to accept that, then you are able to be more flexible in the commit message acceptance, allowing a higher rate of 'happy contributors' don't you think?

btw. all this can be easily avoided adding the 'add a dot if not there' logic to the script that generates the release notes.

**Comment by tiborsimko** [comment]
It depends on the style people would use.  E.g. imagine an informal short style like:

- fixes bug in resumption token parsing

then, by promoting to use full, self-understandable, release-announcement-ready sentences, people are incited to rather write something like:

- Fixes the parsing of resumptiontoken in incoming OAI-PMH XML which could fail when the resumptiontoken was empty.

The final dot is useful when the release news item contains more than one sentence:

- Apache virtual environments are now created with appropriate `WSGIDaemonProcess` user value, taken from the configuration variable `CFG_BIBSCHED_PROCESS_USER`, provided it is set.  This change makes it easier to run Invenio under non-Apache user identity.

Would saving the final dot in the last two examples improve anything?

**Comment by david-caro** [comment]
Nop, but adding it does not improve it either...

And in any case, that can be easily done by the script that parses the commit messages in order to put them in the release notes. Any rule that will force a contributor to manually do anything, is an extra barrier, the more you take away (by automating or removing) the better. And, imo, this one is suitable for both.

**Comment by tiborsimko** [comment]
The contributor is presumably used to writing full English sentences when writing the documentation, the  email conversations, the reports, the papers... The final dot should not be much of a novelty or a burden?

The hope being that using full, self-understandable, release-announcement-ready sentences will lead to better information in the changelog for everybody -- which is the ultimate goal.  (not the dot..)

**Comment by david-caro** [comment]
Exactly what I said, not the dot ;), the dot is totally negligible, so be it

**Comment by tiborsimko** [comment]
It matters if you have more than one sentence in the release news item, as mentioned above [here](https://github.com/inveniosoftware/kwalitee/pull/94#issuecomment-233323585)  and [here](https://github.com/inveniosoftware/kwalitee/pull/94#issuecomment-233344409). 

Information-wise, I'd naturally very much prefer to see this: *(note the missing final dot)*

- Fixes the parsing of resumptiontoken in incoming OAI-PMH XML which could fail when the resumptiontoken was empty

anytime over this: *(note the present final dot)*

- Fixes bug in resumption token parsing.

However, if people take the time to write the former, information-rich message, why wouldn't they add the final dot to end the sentence properly? We are simply sticking to English defaults here; is it a problem? Would anyone ever write multi-sentence paragraphs without final dots, anyway?

**Comment by tiborsimko** [comment]
> I might

I'm curious how would you write the above-quoted multi-sentence news item then?

-  Apache virtual environments are now created with appropriate WSGIDaemonProcess user value, taken from the configuration variable CFG_BIBSCHED_PROCESS_USER, provided it is set. This change makes it easier to run Invenio under non-Apache user identity. 

> you are free to enforce as many rules as you want on your project

We decided about commit message formatting practices among all Invenio contributors together, see e.g. [this RFC](https://github.com/inveniosoftware/invenio/issues/2856). We usually work by consensus. 

If using full English sentences with the final dot in place is really that bothersome to you, we could re-discuss the commit message formatting style again... but I'm curious what would you propose to use as the best common denominator here, taking all our various personal backgrounds and preferences into account, all the while ensuring that the news items would be self-understandable and release-announcement-friendly from the get-go? 

"Stick to English grammar" seemed to be a good neutral common response the last time we discussed the commit message style -- similarly how "stick to PEP-8/PEP-257" seemed to be a good neutral common response the last time we discussed the Python code style.

However, our past decisions are not set in stone,  we can surely re-consider them if you have a good alternative proposal...

**Comment by david-caro** [comment]
That's easy:

```
* Apache virtual environments are now created with appropriate WSGIDaemonProcess user value, taken from the configuration variable CFG_BIBSCHED_PROCESS_USER, provided it is set. This change makes it easier to run Invenio under non-Apache user identity
```
You don't need a period to clearly notice that the sentence ends there.

I thought I already proposed it, letting the machines do all that machine-type work, that is, making the release script itself add the extra dot when generating the release text. As for checking the logs and such, you already agreed that it does not really matter if it has a dot or not in order to read, understand or interpret the commit message.

If you read pep8 for example, they make very clear, that you should not enforce it if it gets in the way of anything, that it is just a guideline to which you might find numerous exceptions. And even then, you have tools that will let you do the formatting for you (autopep8, editor plugins, yapf...) exactly because caring so much about the continent and not about the content is something that a machine can do really well, and they will not complain for doing tedious work (not yet at least).

**Comment by jirikuncar** [comment]
I'm sorry but it really does not make sense to discuss the English grammar here. We do not discuss Python indentation so we should not discuss that a sentence starts with a capital letter and ends with a dot.

**Comment by david-caro** [comment]
@jirikuncar sorry if I confused you, I'm not trying to change English grammar, I'm just discussing the project's use of it, and constructively offering a solution that would still keep the English grammar correctness you want for the release notes, and still ease any contributor experience, same way that for the python indentation (that also has a bunch of grey areas) you would use autopep8 or any other autoformatter to enforce it on a code base, or you would use auto-correction tools on you mobile phone when writing messages to fit 'proper' English grammar.

**Comment by jirikuncar** [comment]
You can consider kwalitee to be our gitmsgstyle (similar to pycodestyle, pydocstyle). Lets close the discussion here. We may continue in Developers Forum not to spam all people watching our issue tracker. I really appreciate your help with the tool and constructive discussion. :+1:

**Comment by tiborsimko** [comment]
@david-caro We are trying to instill the notion that the commit log messages are an important source of information and that they should be self-understandable, information-rich, and user-perspective friendly. They are not meant to be private notes of the original developer. Rather, they are meant to be read by others: the reviewer, the integrator, the fellow developers of other services, the future programmers who will be bisecting our bugs in our code 10 years from now.  Hence our usage of NOTE/FIX/NEW/BETTER/etc labels, hence the recommendation of using full release-announcement friendly sentences.  

Taken from this perspective, you can consider the usage of a full stop at the end of paragraphs as a simple matter of English language convention courtesy towards the readers. Just as developers use full stops when writing issues, wikis, and other reports, let us consider commit log messages to be an equally important source of information, where the same reader-friendly courtesy rules apply.

I'll take this occasion and expand [our notes about current practices](http://invenio.readthedocs.io/en/latest/technology/git.html#remarks-often-made-during-code-review) in the light of our discussion. These practices were written a long time ago and I fully agree that the spirit of "why" may not be very well visible there. 

If you have a proposal for a deep change regarding our commit message style, we can use our regular RFC mechanisms, which I'll also take time to better document [here](http://invenio.readthedocs.io/en/latest/processes/index.html).

P.S. One of advantages when a new staff arrives is that this constitutes a natural point in time to improve our practices and our documentation :smile:

**Pull request merged**
