### PR TITLE
docs: MAINTAINERS file and LGTM configuration

### PR DESCRIPTION
**Pull request by tiborsimko**
* Adds the MAINTAINERS file and the initial LGTM configuration.

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
LGTM

**Comment by tiborsimko** [comment]
LGTM 

(for this initial check; the self-approval will be turned off by this very PR)

**Comment by kaplun** [comment]
How does will work?

**Comment by jirikuncar** [comment]
@kaplun this was a test. The result will be discussed with project maintainers through correct channels. Stay tuned.

**Pull request merged**
